apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  namec: mysql-pvc
  namespace: famousdots
spec:
  accessModes:
    - ReadWriteOnce
  resource:
    requested:
      storage: 1Gi
    storageClassName: gp2