apiVersion: v1 
kind: ConfigMap 
metadata:
  name: {{ .Values.cronjob.configMapName }}
  namespace: {{ .Release.Namespace }}
data: 
  config.properties: |
{{ .Values.cronjob.configmapdata | indent 4 }}
