apiVersion: batch/v1
kind: Cronjob
metadata:
    name: {{ .Chart.Name }}-cronjob
    namespace: {{ .Values.namespace }}
spec:
    schedule: {{ .Values.cronjob.schedule }}
    jobTemplate:
        spec:
            template:
                containers:
                -   name: cron
                    image: "{{ .Values.cronjob.image.repository }}: {{ .Values.cronjob.image.tag }}"
                    imagePullPolicy: Always
                restartPolicy: OnFailure
                