apiVersion: batch/v1
kind: CronJob
metadata:
    name: {{ .Chart.Name }}-cronjob
    namespace: {{ .Release.Namespace  }}
spec:
    schedule: {{ .Values.cronjob.schedule | quote }}
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                    -   name: cron
                        image: "{{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag }}"
                        imagePullPolicy: Always
                        volumeMounts:
                        -   name: config-properties-file
                            mountPath: /app/config.properties
                            subPath: config.properties
                    volumes:
                    -   name: config-properties-file
                        configMap:
                            name: {{ .Values.cronjob.configMapName }}
                    restartPolicy: OnFailure

                