apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name }}-ui
  namespace: {{ .Values.namespace }}
  labels: 
    env: {{ .Values.ui.config.ENV }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-ui
  template:
    metadata:
      labels:
        env: {{ .Values.ui.config.ENV | quote }}
        app: {{ .Chart.Name}}-ui
    spec:
      containers:
        - name: ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ui.service.targetPort }}
          resources:
            limits:
              cpu: {{ .Values.ui.resources.limits.cpu | quote }}
              memory: {{ .Values.ui.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.ui.resources.requests.cpu | quote }}
              memory: {{ .Values.ui.resources.requests.memory | quote }}
          env:
            - name: config
              value: {{ .Values.ui.config.ENV | quote }}

          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.ui.configMapName }}
