apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: famousdots
  namespace: argocd
  labels:
    env: live
spec:
  project: famousdots
  source:
    repoURL: https://github.com/tejaskenny/famosdots.git
    targetRevision: HEAD
    path: famousdots-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: famousdots
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

