apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-api-service
  namespace: {{ .Values.namespace }}
  labels:
    env: {{ .Values.api.config.ENV }}

spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
  selector:
    env: {{ .Values.api.config.ENV }}
    app: {{ .Chart.Name}}-api
