namespace: famousdots
global:
  env: prod

ui:
  image:
    repository: 571631915203.dkr.ecr.eu-north-1.amazonaws.com/famousdots-ui
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  service:
    port: 80
    targetPort: 80
    type: ClusterIP
  configMapName: employee-ui-config
  apiBaseUrl: https://apifam.famousdots.com
  resources:
    limits:
      cpu: "100m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"

api: 
  image:
    repository: 571631915203.dkr.ecr.eu-north-1.amazonaws.com/famousdots-api
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  
  service:
    port: 80
    targetPort: 7080
    type: ClusterIP
  configMapName: api-configmap
  configmapdata: |
    db.url=jdbc:mysql://{{ .Chart.Name }}-mysql-service:{{ .Values.mysql.service.port }}/{{ .Values.cronjob.db.name }}
    db.username={{ .Values.cronjob.db.username }}
    db.password={{ .Values.cronjob.db.userpasswd }}
  db:
    host: employee-mysql-service
    port: 3306
    name: test_db
    username: root
    userpasswd: rootpass
  resources:
    limits:
      cpu: "100m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"
      
mysql:
  image:
    repository: mysql
    tag: 5.7
    pullPolicy: Always
  replicaCount: 1
  rootPasswd: rootpass
  database: test_db
  resources:
    limits:
      cpu: "100m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"
  initScriptConfigMap: mysql-configmap
  initSql: |
    CREATE DATABASE IF NOT EXISTS test_db;

    USE test_db;
    CREATE TABLE IF NOT EXISTS employee (
        id INT PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(100),
        address VARCHAR(200)
    );
  service:
    port: 3306
    targetPort: 3306
    type: ClusterIP
  volume:
    volumeID: vol-0f76830bc59b070f8
    storageClassName: gp2
    storageSize: 1Gi

cronjob:
  image:
    repository: 571631915203.dkr.ecr.eu-north-1.amazonaws.com/famousdots-cron
    tag: latest
  schedule: "*/2 * * * *"
  configMapName: cronjob-configmap
  configmapdata: |
      db.url=jdbc:mysql://{{ .Chart.Name }}-mysql-service:{{ .Values.mysql.service.port }}/{{ .Values.cronjob.db.name }}
      db.username={{ .Values.cronjob.db.username }}
      db.password={{ .Values.cronjob.db.userpasswd }}
  
ingress:
  enabled: true
  uiHost: uifam.famousdots.com
  apiHost: apifam.famousdots.com
  certificateArn: arn:aws:acm:eu-north-1:571631915203:certificate/3726c6e6-c6de-45fc-bb70-e76497b8245e   