apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api-stateful
  namespace: famousdots
  labels:
    setup: prod
spec:
  serviceName: "api-headless"  # Headless service for stable network ID
  replicas: 1
  selector:
    matchLabels:
      setup: api
      env: prod
  template:
    metadata:
      labels:
        env: prod
        setup: api
    spec:
      containers:
        - name: api
          image: 571631915203.dkr.ecr.eu-north-1.amazonaws.com/famousdots-api:latest
          ports:
            - containerPort: 7080
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config-property
              mountPath: /app/config.properties
              subPath: config.properties
      volumes:
        - name: config-property
          configMap:
            name: api-configmap
