apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Chart.Name }}-pvc
    namespace: {{ .Release.Namespace }}
spec:
    accessModes:
        -   ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.mysql.volume.storageSize }}
    storageClassName: {{ .Values.mysql.volume.storageClassName }}