apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Chart.Name }}-pvc
    namespace: {{ .Values.namespace }}
spec:
    accessModes:
        -   ReadWriteOnly
    resources:
        request:
            storage: {{ .Values.mysql.volume.storageSize }}
    storageClassName: {{ .Values.mysql.volume.storageClassName }}