apiVersion: v1
kind: Secret

metadata: 
    name: {{ .Chart.Name }}-secret-mysql
    namespace: {{ .Release.Namespace }}

type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPasswd | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.database | quote }}
