apiVersion: v1
kind: Service
metadata:
  name: employee-mysql-service
  namespace: famousdots
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: employee-mysql
